### ISSUE TITLE
Namespace Gst not avaiable

### ISSUE THREAD

**Issue by phbaars** [reinzor/videowall#10]
Installation on RasberryPi and Ubuntu went fine. 
When I start /scripts/client it needs more arguments, I tried client rpi eth0 but it complains "network is unreachable"  while I can ping the server. Does the pi need an ip address to work?
When I start /scripts/web_server on Ubuntu it complains "Namespace GST not available".

Could you please give a description of the purpose of all the files in /scripts and /test, and also a working example setup for a working video wall? Especially an example to play a video on the server that is displayed by the client?

Also a description on how the system is supposed to work would be most welcome.
Thanks

**Comment by reinzor** [comment]
> Does the pi need an ip address to work?

Yes, could you provide a log?

> When I start /scripts/web_server on Ubuntu it complains "Namespace GST not available".

Hmm, most probably a different gstreamer version, output log?

>Could you please give a description of the purpose of all the files in /scripts and /test, and also a working example setup for a working video wall? Especially an example to play a video on the server that is displayed by the client?
>Also a description on how the system is supposed to work would be most welcome.

*client* runs on every raspberry pi and renders a tile of a video (or a mirror)
*server* servers as time server for synchronized video playback and entrypoint for the player. The server serves a webserver.

**Comment by reinzor** [comment]
Installation / usage instruction https://youtu.be/XLXoX8bj2vA

**Comment by phbaars** [comment]
Web_server will start if you install gir1.2-streamer-1.0 and gir1.2-gst-plugins-base-1.0
Now, when you start a file in the playlist it complains that the file cannot be opened. Any idea? I placed the file ella.mp4 in ~/Videos myself. See picture.
![error](https://user-images.githubusercontent.com/1737664/69831946-fdd96d00-122b-11ea-99ba-5e552b9a0007.jpg)

**Comment by reinzor** [comment]
libmediainfo-dev seems to be missing. Just added that to the install script.

**Comment by phbaars** [comment]
<libmediainfo-dev seems to be missing. Just added that to the install script.
I think you should add gir1.2-streamer-1.0 and gir1.2-gst-plugins-base-1.0 too. I will test again tomorrow.

**Comment by phbaars** [comment]
Webserver works! Still some questions:
1) is the webserver supposed to play sound too?
2) where is the file to control the monitor position/tile sizes in the videowall?
3) how do I get rid of the timer and ip number on the screens?
Keep up the good work!

**Comment by reinzor** [comment]
Good news, please post some photos videos of the setup if you have the chance.

1. Nope, not implemented, only video sinks
2. You can to this via the Web interface (icon top right if I remember correctly) 
3. You can't at the moment. I could create this feature. Please open a new issie with a feature request.
