### ISSUE TITLE
Wiring and screen capabilities 

### ISSUE THREAD

**Issue by elizabethlewin** [reinzor/videowall#4]
I cannot tell from your documentation--  can you have the video span more than 2 screens? I noticed you had 4 screens running videos but only two screens were connected. Is it possible to have more than two screens playing the same video? 

How did you connect the Pi Zero to the Raspberry Pi master? WiFi connection? 

Super interested in this project. I am a student and just learning how to program and I thought this would be a good project to learn from! 

Thanks so much!

**Comment by reinzor** [comment]
Hi Elizabeth,

This project is still a work in progress. Currently the following features are implemented:
- Web + clock server for playback (running on linux, not tested on raspberry pi yet)
  - Video upload (only x264 720p videos)
  - Starting different video files
  - Drag / drop / resize screens from clients
- Linux client for playback
- Raspberry pi client for playback
- Video's on clients play synchronized on the server clock

I did a setup with two screens that both play 50% of the movie, the tiles can be configured with use of the web server. However, I still have some performance issues with multiple clients that play smaller tiles of the base video. However, synchronized playback (non-tiled) works with multiple clients.

As for the clients I use raspberry pi zero's with a micro-usb ethernet dongle. I also tested on a Raspberry pi 3. An experiment I did last weekend involved 6 raspberry pi zero clients but I think the system should easily handle 10+ clients, maybe much more but I need to test this.

![20190113_144055](https://user-images.githubusercontent.com/4176023/51199448-06b49f00-18f7-11e9-9850-22c0b4f67a8b.jpg)

It is still a work in progress and I am working on a raspberry pi image that you can just write to your raspberry pi sd card.

**Comment by reinzor** [comment]
Just made an image release for testing purposes:

https://github.com/reinzor/videowall/releases/tag/0.1

This version should be able to crop and upscale.

**Comment by reinzor** [comment]
> can you have the video span more than 2 screens?

Yes, see https://www.youtube.com/watch?v=f5Dp35RL9q8

> How did you connect the Pi Zero to the Raspberry Pi master? WiFi connection?

I used usb to ethernet adapters, see https://github.com/reinzor/videowall#hardware

I will close this issue since all questions has been answered
